Repository adopted-ember-addons/ember-cli-flash, pull requests merged in 2022-06, with the labels that each got.

#383 ember-cli 4.4.0, remove auto service injection
  .editorconfig
  .ember-cli
  .github/workflows/ci.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  addon/flash/object.js
  addon/services/flash-messages.js
  addon/utils/flash-message-options.js
  app/initializers/flash-messages.js
  blueprints/ember-cli-flash/index.js
  config/ember-try.js
  package.json
  testem.js
  tests/dummy/app/app.js
  tests/dummy/app/index.html
  tests/dummy/app/router.js
  tests/dummy/app/templates/application.hbs
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/environment.js
  tests/dummy/config/optional-features.json
  tests/helpers/index.js
  tests/index.html
  tests/integration/components/flash-message-test.js
  tests/unit/flash/object-test.js
  tests/unit/services/flash-messages-test.js
  tests/unit/utils/computed-test.js
  tests/unit/utils/get-with-default-test.js
  yarn.lock
Labels: breaking

#377 Update README.md formatting
  README.md
Labels: documentation

#382 Convert `flash-message` to Glimmer component
  addon/components/flash-message.hbs
  addon/components/flash-message.js
  package.json
  yarn.lock
Labels: breaking

#384 Allow arbitrary properties in `MessageOptions` interface
  index.d.ts
Labels: bug

#366 Fix types for service
  index.d.ts
Labels: bug
