Repository adopted-ember-addons/ember-cli-flash, pull requests merged in 2024-02, with the labels that each got.

#400 Setup relase plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  RELEASE.md
  ember-cli-flash/package.json
  package.json
  pnpm-lock.yaml
  test-app/package.json
Labels: internal

#402 Bump ember-qunit in test-app
  pnpm-lock.yaml
  test-app/package.json
Labels: internal

#404 Publish files
  ember-cli-flash/package.json
Labels: bug

#399 fix(types): add typesVersions map
  ember-cli-flash/package.json
Labels: bug

#405 Add `FlashMessage` to TypeScript definitions
  ember-cli-flash/declarations/components/flash-message.d.ts
Labels: enhancement

#407 Update release-plan to get the latest bugfixes
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal
